name: ğŸ“ â€¢ CodeQL

on:
  workflow_call:
    inputs:
      cmake-args:
        description: "Additional arguments to pass to CMake"
        default: ""
        type: string

jobs:
  analyze-cpp:
    name: ğŸ‡¨â€Œ
    uses: ./.github/workflows/reusable-code-ql-cpp.yml
    with:
      cmake-args: ${{ inputs.cmake-args }}

  analyze-python:
    name: ğŸ
    uses: ./.github/workflows/reusable-code-ql-python.yml
