name: ğŸ“ â€¢ CodeQL

on:
  workflow_call:

jobs:
  analyze-cpp:
    name: ğŸ‡¨â€Œ
    uses: ./.github/workflows/reusable-code-ql-cpp.yml

  analyze-python:
    name: ğŸ
    uses: ./.github/workflows/reusable-code-ql-python.yml
